# Lab 4

In [1]:
from sympy import *

def derivate2(expr, s):
    x, y = symbols('x y')
    # expr = x**2 + 2 * y + y**3
    expr_diff = Derivative(expr, s)
    # print("Value of the derivative : {}".format(expr_diff.doit()))
    return expr_diff.doit()

expr = input("Enter equation: (x**2 + 2 * y + y**3)")
f1 = derivate2(expr,  symbols('x'))
f2 = derivate2(expr,  symbols('y'))

print(f1)
print(f2)

SympifyError: Sympify of expression 'could not parse ''' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 0)

In [ ]:
from scipy.optimize import minimize
import numpy as np

# Define the objective function and its Hessian matrix
def objective_function(x):
    return x[0]**2 + x[1]**2

def hessian_matrix(x):
    return np.array([[2, 0], [0, 2]])

# Define constraints (if any)
constraints = ({'type': 'eq', 'fun': lambda x: x[0] + x[1] - 1})

# Define an initial guess
initial_guess = [0.5, 0.5]

# Perform optimization
result = minimize(objective_function, initial_guess, constraints=constraints)

# Display the result
print("Optimal values:", result.x)
print("Optimal objective function value:", result.fun)

# Calculate and print the Hessian matrix
hessian_matrix_result = hessian_matrix(result.x)
print("\nHessian Matrix:")
print(hessian_matrix_result)

Optimal values: [0.5 0.5]
Optimal objective function value: 0.5

Hessian Matrix:
[[2 0]
 [0 2]]


In [ ]:
from sympy import *

x1, x2 = symbols('x1, x2')
theta = Symbol("theta")

# Define the function
f = x1**2 + 2 * x2 + x2**3

# Calculate the Hessian matrix of f at x = [x1, x2]
H = hessian(f, [x1, x2])

H

Matrix([
[2,    0],
[0, 6*x2]])

In [ ]:
# import sympy 
from sympy import *

x, y = symbols('x y')
expr = x**2 + 2 * y + y**3
print("Expression : {}".format(expr))

# Use sympy.Derivative() method 
expr_diff = Derivative(expr, x) 
	
print("Derivative of expression with respect to x : {}".format(expr_diff)) 
from sympy import *
print("Value of the derivative : {}".format(expr_diff.doit()))

Expression : x**2 + y**3 + 2*y
Derivative of expression with respect to x : Derivative(x**2 + y**3 + 2*y, x)
Value of the derivative : 2*x


In [ ]:
import sympy as sympy

def derivate2(expr, s):
    x, y = symbols('x y')
    # expr = x**2 + 2 * y + y**3
    expr_diff = Derivative(expr, s)
    # print("Value of the derivative : {}".format(expr_diff.doit()))
    return expr_diff.doit()

def derivate3(expr, s):
    x, y, z = symbols('x y z')
    # expr = x**2 + 2 * y + y**3
    expr_diff = Derivative(expr, s)
    # print("Value of the derivative : {}".format(expr_diff.doit()))
    return expr_diff.doit()

x = (int)(input("Enter number of variables: "))

if (x == 2):
    x, y = symbols('x y')
    expr = input("Enter equation: (x**2 + 2 * y + y**3)")
    # f1 = Derivative(expr, x)
    f1 = derivate2(expr,  symbols('x'))
    f2 = derivate2(expr,  symbols('y'))

    a = sympy.solve(f1)
    b = sympy.solve(f2)
    print(a)
    print(b)

    h11 = derivate2(f1,  symbols('x'))
    h12 = derivate2(f1,  symbols('y'))
    h21 = derivate2(f2,  symbols('x'))
    h22 = derivate2(f2,  symbols('y'))

    Hess = np.matrix([[h11.subs({x: 0, y: 0}), h12.subs({x: 0, y: 0})],
                    [h21.subs({x: 0, y: 0}), h22.subs({x: 0, y: 0})]])
    print(Hess)
elif (x == 3):
    x, y, z = symbols('x y z')
    expr = input("Enter equation: (x**2 + 2 * y + y**3)")
    # f1 = Derivative(expr, x)
    f1 = derivate2(expr,  symbols('x'))
    f2 = derivate2(expr,  symbols('y'))
    f3 = derivate2(expr,  symbols('z'))

    a = sympy.solve(f1)
    b = sympy.solve(f2)
    c = sympy.solve(f3)
    print(a)
    print(b)
    print(c)

    h11 = derivate2(f1,  symbols('x'))
    h12 = derivate2(f1,  symbols('y'))
    h13 = derivate2(f1,  symbols('z'))
    h21 = derivate2(f2,  symbols('x'))
    h22 = derivate2(f2,  symbols('y'))
    h23 = derivate2(f2,  symbols('z'))
    h31 = derivate2(f3,  symbols('x'))
    h32 = derivate2(f3,  symbols('y'))
    h33 = derivate2(f3,  symbols('z'))

    Hess = np.matrix([[h11.subs({x: 0, y: 0, z:0}), h12.subs({x: 0, y: 0, z:0}), h13.subs({x: 0, y: 0, z:0})],
                        [h21.subs({x: 0, y: 0, z:0}), h22.subs({x: 0, y: 0, z:0}), h23.subs({x: 0, y: 0, z:0})],
                        [h31.subs({x: 0, y: 0, z:0}), h32.subs({x: 0, y: 0, z:0}), h33.subs({x: 0, y: 0, z:0})]])
    print(Hess)

[0]
[-sqrt(6)*I/3, sqrt(6)*I/3]
[[2 0]
 [0 0]]


In [ ]:
from sympy.abc import x, y
from sympy import ordered, Matrix, hessian

eq = x**2/2 + 5*y**2 + 2*(x - 2)**4/3 + 8*(y + 1)**4

v = list(ordered(eq.free_symbols)); v

[x, y]

In [ ]:
gradient = lambda f, v: Matrix([f]).jacobian(v)

gradient(eq, v)
# Matrix([[x + 8*(x - 2)**3/3, 10*y + 32*(y + 1)**3]])

Matrix([[x + 8*(x - 2)**3/3, 10*y + 32*(y + 1)**3]])

In [ ]:
hessian(eq, v)
# Matrix([
        # [8*(x - 2)**2 + 1,                  0],
        # [               0, 96*(y + 1)**2 + 10]])

Matrix([
[8*(x - 2)**2 + 1,                  0],
[               0, 96*(y + 1)**2 + 10]])

**Portfolio Selection**

Portfolio Selection: An investor has $5000 and two potential investments. Let x j for j = 1 and j = 2 denote his allocation to investment j in thousands of dollars. From historical data, investments 1 and 2 have an expected annual return of 20 and 16 percent, respectively. Also, the total risk involved with investments 1 and 2, as measured by the variance of total return, is given by 2x12 + x22 + (x1 + x2 )2 , so that risk increases with total investment and with the amount of each individual investment. The investor would like to maximize his expected return and at the same time minimize his risk. Clearly, both of these objectives cannot, in general, be satisfied simultaneously. There are several possible approaches. For example, he can minimize risk subject to a constraint imposing a lower bound on expected return. Alternatively, expected return and risk can be combined in an objective function, to give the model:

Maximize f (x) = 20x1 + 16x2 − θ [2x12 + x22 + (x1 + x2 )2 ],
subject to:
g1 (x) = x1 + x2 ≤ 5,
x1 ≥ 0, x2 ≥ 0, (that is, g2 (x) = −x1, g3 (x) = −x2 ).

The nonnegative constant θ reflects his tradeoff between risk and return. If θ = 0, the model is a linear program, and he will invest completely in the investment with greatest expected return. For very large θ , the objective contribution due to expected return becomes negligible and he is essentially minimizing his risk.

In [ ]:
# Portfolio Selection

from scipy.optimize import minimize
import numpy as np

# Objective function
def objective(x, theta):
    return -(20*x[0] + 16*x[1] - theta*(2*x[0]**2 + x[1]**2 + (x[0] + x[1])**2))

# Constraints
def constraint(x):
    return x[0] + x[1] - 5

# Lagrange multiplier calculation
def lagrange_multiplier(x, theta):
    return 4*theta*x[0] + 2*theta*(x[0] + x[1])

# Gradient of the objective function
def gradient(x, theta):
    return np.array([-40*x[0] - 4*theta*x[0] - 2*theta*(x[0] + x[1]),
                     -32*x[1] - 2*theta*x[1] - 2*theta*(x[0] + x[1])])

# Hessian matrix of the Lagrangian
def hessian(x, theta):
    return np.array([[-4*theta - 2*theta, -2*theta],
                     [-2*theta, -2*theta]])

# Initial guess
x0 = [2, 3]
theta = 1  # Choose an appropriate value for theta

# Solve optimization problem
result = minimize(lambda x: objective(x, theta), x0, constraints={'type': 'eq', 'fun': constraint})

# Extract optimal values
optimal_x = result.x
optimal_objective = -result.fun

# Calculate Lagrange multiplier
lambda_value = lagrange_multiplier(optimal_x, theta)

# Calculate Hessian matrix
hess = hessian(optimal_x, theta)

# Print results
print("Optimal allocation:", optimal_x)
print("Optimal objective value:", optimal_objective)
print("Lagrange multiplier:", lambda_value)
print("Hessian matrix:")
print(hess)

Optimal allocation: [2.33333333 2.66666667]
Optimal objective value: 46.33333333333333
Lagrange multiplier: 19.333333333333332
Hessian matrix:
[[-6 -2]
 [-2 -2]]


**Water Resources Planning**

In regional water planning, sources emitting pollutants might be required to
remove waste from the water system. Let x j be the pounds of Biological Oxygen Demand (an often-used
measure of pollution) to be removed at source j.
One model might be to minimize total costs to the region to meet specified pollution standards:

Minimize sigma(j=1, n)[fi(xi)]

subject to:
sigma(j=1, n)[aij * xj ≥ bi]     (i = 1, 2, . . . , m)
0 ≤ xj ≤ uj      ( j = 1, 2, . . . , n),

where
fj(xj) = Cost of removing x j pounds of Biological Oxygen Demand at source j,
bi = Minimum desired improvement in water quality at point i in the system,
aij = Quality response, at point i in the water system, caused by removing one pound of Biological Oxygen Demand at source j,
uj = Maximum pounds of Biological Oxygen Demand that can be removed at source j.

In [ ]:
# Water Resources Planning

from scipy.optimize import minimize

# Water Resources Planning
# Define the cost functions fj(xj) for water resources planning
def cost_function_j1(x):
    return x  # Define your cost function for source 1 here

def cost_function_j2(x):
    return x  # Define your cost function for source 2 here

def cost_function_j3(x):
    return x  # Define your cost function for source 3 here

# Define the quality response matrix aij for water resources planning
a_ij1 = 1.0
a_ij2 = 2.0
a_ij3 = 3.0

# Define the minimum desired improvement vector bi for water resources planning
b1 = 10.0
b2 = 15.0
b3 = 20.0

# Define the maximum pounds of BOD vector uj for water resources planning
u1 = 5.0
u2 = 10.0
u3 = 15.0

# Define the initial guess for water resources planning
x0_water_resources = [0.0, 0.0, 0.0]

# Define the objective function for water resources planning
def f(x):
    return sum(fj(x[j]) for j in range(len(x)))

# Define the constraints for water resources planning
def constraint(x):
    return [sum(a[i][j] * x[j] for j in range(len(x))) - b[i] for i in range(len(a))]

# Define the cost functions fj(xj) for water resources planning
fj = [cost_function_j1, cost_function_j2, cost_function_j3]

# Define the quality response matrix aij for water resources planning
a = [[a_ij1, a_ij2, a_ij3],
     [a_ij1, a_ij2, a_ij3],
     [a_ij1, a_ij2, a_ij3]]

# Define the minimum desired improvement vector bi for water resources planning
b = [b1, b2, b3]

# Define the maximum pounds of BOD vector uj for water resources planning
u = [u1, u2, u3]

# Solve the optimization problem for water resources planning
result_water_resources = minimize(f, x0_water_resources, constraints={'type': 'ineq', 'fun': constraint})

# Portfolio Selection
# Define the objective function for portfolio selection
def portfolio_objective(x, theta):
    return 20*x[0] + 16*x[1] - theta*(2*x[0]**2 + x[1]**2 + (x[0] + x[1])**2)

# Define the constraints for portfolio selection
def portfolio_constraint(x):
    return x[0] + x[1] - 5

# Define the Hessian matrix of the Lagrangian for portfolio selection
def portfolio_hessian(x, theta):
    return [[-4*theta - 2*theta, -2*theta],
            [-2*theta, -2*theta]]

# Initial guess for portfolio selection
x0_portfolio = [2, 3]

# Choose a value for theta for portfolio selection
theta_portfolio = 1  # You can adjust this value as needed

# Solve the optimization problem for portfolio selection
result_portfolio = minimize(lambda x: portfolio_objective(x, theta_portfolio), x0_portfolio, constraints={'type': 'eq', 'fun': portfolio_constraint})

# Calculate the Hessian matrix for portfolio selection
hessian_portfolio = portfolio_hessian(result_portfolio.x, theta_portfolio)

# Print the results
print("Water Resources Planning - Optimal BOD removal:", result_water_resources.x)
print("Water Resources Planning - Minimum total cost:", result_water_resources.fun)
print("\nPortfolio Selection - Optimal allocation:", result_portfolio.x)
print("Portfolio Selection - Maximum expected return:", -result_portfolio.fun)
print("Portfolio Selection - Hessian matrix:")
print(hessian_portfolio)

TypeError: 'list' object is not callable